baseURL = 'https://aaroh.github.io/'
languageCode = 'en-us'
title = "Aaroh's Blog"
theme = 'PaperMod'

PluralizeListTitles = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "technical"
    name = "Technical"
    url = "/technical/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 5
  

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[params]
  math = true
  ShowAllPagesInArchive = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  ShowReadingTime = true
  RobotsNoIndex = false

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true
