baseURL = 'https://aaroh.github.io/'
languageCode = 'en-us'
title = "Aaroh's Blog"
theme = 'PaperMod'

PluralizeListTitles = false

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "technical"
    name = "Technical"
    url = "/technical/"
    weight = 2

  [[menu.main]]
    identifier = "archives"
    name = "Archive"
    url = "/archives/"
    weight = 5
  

[outputs]
  home = ['html', 'rss']
  page = ['html']
  rss = ['rss']
  section = ['html', 'rss']
  taxonomy = ['html', 'rss']
  term = ['html', 'rss']

[params]
  math = true
  ShowAllPagesInArchive = true
  ShowCodeCopyButtons = true
  ShowFullTextinRSS = true
  ShowReadingTime = true
  RobotsNoIndex = false
  defaultTheme = "light"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
    unsafe = true



[params.profileMode]
enabled = true
title = "Aaroh's Blog"
subtitle = "CS Articles and Project Reports"
imageUrl = "/me.jpg"
imageTitle = "Da Goat"
imageWidth = 120
imageHeight = 120

    [[params.profileMode.buttons]]
  name = "Technical Articles"
  url = "/technical"

  [[params.profileMode.buttons]]
  name = "Projects"
  url = "/projects"

  [[params.profileMode.buttons]]
  name = "Music Recommendations"
  url = "/music/"


[[params.socialIcons]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/aaroh-gokhale-14976b20a/"

[[params.socialIcons]]
name = "X"
url = "https://x.com/aarohgokhale"

[[params.socialIcons]]
name = "GitHub"
url = "https://github.com/gokhaleaaroh"

[[params.socialIcons]]
name = "Codeberg"
url = "https://codeberg.org/aaroh"

[[params.socialIcons]]
name = "RSS"
url = "/index.xml"
